### ISSUE TITLE
Release to ros buildfarm

### ISSUE THREAD

**Issue by Timple** [Autoware-AI/core_perception#7]
## Feature request
Release `points_preprocessor` to the ROS buildfarm. 

### Description

We're using the `ray_ground_filter` from the `points_preprocessor` package. But installation and compilation takes quite some time because of the dependencies. So would it be possible to release for melodic and noetic?

### Implementation considerations

I can imagine it might be undesired to release a single package from this complete repository, but it might be a nice starting point.

### Alternatives

Fork the single `points_preprocessor` package, strip the autoware dependencies such as `autoware_health_checker`. This last one has heavy dependencies and is not required for operation.
But I'd rather stick to the original version here of course. For credibility and maintenance reasons :)

**Comment by JWhitleyWork** [comment]
@Timple Unfortunately, we are not targeting any of these packages for release to the ROS Build Farm at this time - primarily because the code is not in a state where each package can build independently for the build farm. We're not opposed to someone forking the code and releasing packages on the build farm but we don't have the resources to dedicate to this task for Autoware.AI at this time (we are mostly focused on Autoware.AUTO which is ROS2-based). Please let me know if this answers your question.

**Comment by Timple** [comment]
That does answer my question!
I'll try to go through the effort of releasing only `points_preprocessor`. (And more if we need more in the future)
